---

name: Daily

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "0 5 * * *"

jobs:
  publish_docker:
    name: Publish Docker
    runs-on: ubuntu-latest
    needs: publish_platform

    strategy:
      matrix:
        runtime:
          - name: daily-x86_64
            packages: io.elementary.Platform/x86_64/daily io.elementary.Sdk/x86_64/daily
            tag: daily
          - name: daily-aarch64
            packages: io.elementary.Platform/aarch64/daily io.elementary.Sdk/aarch64/daily
            tag: daily-aarch64
          - name: stable-6-x86_64
            packages: io.elementary.Platform/x86_64/6 io.elementary.Sdk/x86_64/6
            tag: '6'
          - name: stable-6-aarch64
            packages: io.elementary.Platform/aarch64/6 io.elementary.Sdk/aarch64/6
            tag: 6-aarch64

    services:
      registry:
        image: registry:latest
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & push the base image to local registry
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: localhost:5000/fedora-base:latest

      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          cat >> ${{ matrix.runtime.name }}.Dockerfile << EOF
          # syntax = docker/dockerfile:experimental
          FROM localhost:5000/fedora-base:latest
          RUN --security=insecure flatpak install -y --noninteractive appcenter ${{ matrix.runtime.packages }}

      - name: Build & push the ${{ matrix.runtime.name }} image
        uses: docker/build-push-action@v2.2.2
        with:
          allow: security.insecure
          context: .
          file: ${{ matrix.runtime.name }}.Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}/runtime
          tags: ${{ matrix.runtime.tag }}
